version: '3.9'

services:
  backend:
    build: ./backend
    image: dentex-backend:latest
    container_name: dentex-backend
    volumes:
      - "./backend:/app"
    ports:
      - "8080:8080"
    restart: always
    shm_size: '2gb'
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_CPP_MIN_LOG_LEVEL=2

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8080
    image: dentex-frontend:latest
    container_name: dentex-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
