# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7fXFgaBDHNAShaII5es-QIk9zy1d8_1
"""

# Dependencies are now managed via requirements.txt

import os
import shutil
from pathlib import Path
from google.cloud import storage
from ultralytics import YOLO

from config import PROJECT_ID, DATASET_BUCKET, ARTIFACT_BUCKET, MODEL_BUCKET, DEFAULT_EPOCHS, DEFAULT_BATCH, DEFAULT_IMGSZ

DATASET_PREFIX = "dentex-seg"      # Change according to your bucket

LOCAL_DATASET = Path("/workspace/dataset")

# Authentication is handled by standard Application Default Credentials (ADC)

client = storage.Client()

bucket = client.bucket(DATASET_BUCKET)

if LOCAL_DATASET.exists():
    shutil.rmtree(LOCAL_DATASET)

LOCAL_DATASET.mkdir(parents=True)

blobs = client.list_blobs(
    DATASET_BUCKET,
    prefix=DATASET_PREFIX
)

for blob in blobs:

    if blob.name.endswith("/"):
        continue

    relative = blob.name[len(DATASET_PREFIX):].lstrip("/")

    destination = LOCAL_DATASET / relative

    destination.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    blob.download_to_filename(str(destination))

print("Dataset Downloaded")

import argparse

model = YOLO("yolov8m-seg.pt")

parser = argparse.ArgumentParser()
parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
parser.add_argument("--batch", type=int, default=DEFAULT_BATCH)
parser.add_argument("--imgsz", type=int, default=DEFAULT_IMGSZ)
parser.add_argument("--lr0", type=float, default=0.001)

args = parser.parse_args()

results = model.train(
    data="/workspace/dataset/data.yaml",
    epochs=args.epochs,
    imgsz=args.imgsz,
    batch=args.batch,
    workers=4,
    project="runs",
    name="dentex-yolov8m-seg"
)

metrics = model.val()

print(metrics)
model.predict(
    source="/workspace/dataset/images/test",
    save=True
)

client = storage.Client()

bucket = client.bucket(ARTIFACT_BUCKET)

local_folder = "runs"

for root, dirs, files in os.walk(local_folder):

    for file in files:

        local_path = os.path.join(root, file)

        blob_path = local_path

        blob = bucket.blob(blob_path)

        blob.upload_from_filename(local_path)

print("Artifacts Uploaded")